### ISSUE TITLE
muxer closed locally

### ISSUE THREAD

**Issue by bakhshandeh** [ChainSafe/js-libp2p-yamux#55]
We have a network of libp2p nodes. All of the nodes run on public IPs and a fixed port.
Sometimes some of the nodes throw this error and the connection between them gets disconnected.

```
CodeError: muxer closed locally
YamuxMuxer.newStream (file:///root/node_modules/@chainsafe/libp2p-yamux/src/muxer.ts:172:13)
ConnectionImpl.newStream [as _newStream] (file:///root/node_modules/libp2p/src/upgrader.ts:437:41)
ConnectionImpl.newStream (file:///root/node_modules/libp2p/src/connection/index.ts:117:31)
EventTarget.dialProtocol (file:///root/node_modules/libp2p/src/libp2p.ts:299:23)
```

Each node is a Node.js process and it may sometimes restart.
The error throws here:
https://github.com/ChainSafe/js-libp2p-yamux/blob/dc55dcf4972c4805cebea4c3a4c18eafc9d17adc/src/muxer.ts#L172

and value of `this.localGoAway` is `NormalTermination`.

Is this an issue on yamux or libp2p?

**Comment by bakhshandeh** [comment]
"@chainsafe/libp2p-yamux": "^4.0.1"
"libp2p": "^0.45.2",

**Comment by wemeetagain** [comment]
closing as stale
