### ISSUE TITLE
KeepAlive Functionality

### ISSUE THREAD

**Issue by justin0mcateer** [ChainSafe/js-libp2p-yamux#76]
What is the intended function of the keepAlive functionality? Is it intended to only send pings blindly with no regard for the outcome? The keepAlive logic doesn't appear to close the stream or emit any event on ping failures. It doesn't appear to track the number of ping failures.

We are having issues with WebSockets staying open for long periods of time when the other side has failed/stopped uncleanly. We have keepAlive enabled and the interval set to 27 seconds. 

To overcome this, we have implemented a periodic ping at the application layer, using the Ping protocol, and we track the number of failed connections and force the connection closed if necessary. However, this is fairly complex thing to manage at the application level and it seems like the keepAlive functionality in the muxer might be a more sensible place for this functionality.

**Comment by achingbrain** [comment]
KeepAlive is not mentioned in the [Yamux spec](https://github.com/hashicorp/yamux/blob/master/spec.md) but looking a [the implementation](https://github.com/hashicorp/yamux/blob/6034404dc2abfb5729aa09bf3a90621d9718b433/session.go#L362-L380) if the keepalive ping fails the connection should be closed.

It looks like we just [ignore any keepalive faliures](https://github.com/ChainSafe/js-libp2p-yamux/blob/87b4db9a8deb300cb2ba6efe09b0cc13a08c90b3/src/muxer.ts#L171) here which is probably incorrect.
